services:
  db:
    ports: !override []
  umami-db:
    ports: !override []
  pgadmin:
    ports: !override []
  web-fastapi:
    ports: !override []
    volumes: !override
    - ./migrations:/app/migrations
    - graph_cache:/app/graph_generation/cache
  umami:
    ports: !override []
