services:
  db:
    image: postgres:16-alpine
    env_file:
      - path: example.env
        required: true
      - path: .env
        required: false
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"] 
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: gunicorn -c src/gunicorn.config.py src.app:app ### Use this command for prod 
    ### command: flask run --host=0.0.0.0 --port=5000 --debug ### Use this command for dev logs --> easier debugging + more info on errors
    volumes:
      # this mounts the entire src (backend python flask / FastAPI) folder
      - ./src:/app/src

      # this mounts other important folders
      - ./templates:/app/templates
      - ./static:/app/static
      - ./migrations:/app/migrations
      - ./graph_generation:/app/graph_generation
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - GUNICORN_WORKERS=2 
      - GUNICORN_LOG_LEVEL=info
      - PYTHONPATH=/app/src

      ### DEBUGGING ENVIRONMENT VARIABLES ###
      # Uncomment the lines below for local development debugging
      # - FLASK_DEBUG=1
      # - LOAD_GRAPH_ON_IMPORT=0    # 0 stops graph loading on import for fast hot-reloads
      # - FLASK_ENV=development
    ports:
      - "5000:5000"
    env_file:
      - path: example.env
        required: true
      - path: .env
        required: false
    depends_on:
      db:
        condition: service_healthy
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crestr-pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_CONFIG_SERVER_MODE: '${PGADMIN_SERVER_MODE}'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: '${PGADMIN_MASTER_REQ}'
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: