"""Added new raw_km distance attribute in the route table

Revision ID: 11512a7425ad
Revises: d9346fc2e12b
Create Date: 2026-05-22 09:51:46.536953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11512a7425ad'
down_revision = 'd9346fc2e12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_km', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('distance_km')

    # ### end Alembic commands ###
