"""Amended settings table

Revision ID: 78f1b406b8b8
Revises: 200dd310335c
Create Date: 2026-05-20 19:29:47.641866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f1b406b8b8'
down_revision = '200dd310335c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('value', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('settings_type_key'), type_='unique')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('settings_type_key'), ['type'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('value')
        batch_op.drop_column('key')

    # ### end Alembic commands ###
