"""Add created_at default to all tables

Revision ID: 8b6749758e3c
Revises: ee5f6163eaa0
Create Date: 2026-07-29 18:52:15.481643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6749758e3c'
down_revision: Union[str, Sequence[str], None] = 'ee5f6163eaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_action_log_action_created'), table_name='action_log')
    op.create_index('index_action_log_action_created', 'action_log', ['action', 'created_at'], unique=False)
    op.drop_constraint(op.f('user_username_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_username_key'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index('index_action_log_action_created', table_name='action_log')
    op.create_index(op.f('idx_action_log_action_created'), 'action_log', ['action', 'created_at'], unique=False)
    # ### end Alembic commands ###
