"""Removed legacy distance string column

Revision ID: b187edc3c417
Revises: c398ff39d261
Create Date: 2026-05-25 07:56:01.119619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b187edc3c417'
down_revision = 'c398ff39d261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('distance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
