"""Add issues table

Revision ID: ca5bbea5443f
Revises: 8ec1adbe9f72
Create Date: 2026-07-13 21:36:02.331142
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca5bbea5443f'
down_revision: Union[str, Sequence[str], None] = '8ec1adbe9f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('title', sa.VARCHAR(length=100), nullable=False),
        sa.Column('description', sa.VARCHAR(length=1000), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), 
                  server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('issues_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues')
    # ### end Alembic commands ###